#!/bin/bash

echo "🚀 Deploy Blueprint Material Analyzer to Your Vercel Account"
echo "==========================================================="
echo ""

echo "📋 Quick Setup Instructions:"
echo ""
echo "1. Go to: https://vercel.com"
echo "2. Sign up/Login with your GitHub account (@SteppieD)"
echo "3. Click 'Add New...' → 'Project'"
echo "4. Import from Git Repository:"
echo "   - Select: SteppieD/blueprint"
echo "   - Click 'Import'"
echo ""
echo "5. Configure Project:"
echo "   - Project Name: blueprint-material-analyzer"
echo "   - Framework: Next.js (auto-detected)"
echo "   - Root Directory: ./"
echo "   - Build Command: npm run build"
echo "   - Output Directory: .next"
echo "   - Install Command: npm install"
echo ""
echo "6. Click 'Deploy' ✅"
echo ""
echo "🎯 Expected Result:"
echo "- Your own Vercel URL: https://blueprint-material-analyzer-[random].vercel.app"
echo "- Custom domain options available"
echo "- Automatic deployments on GitHub pushes"
echo ""
echo "⚡ The whole process takes about 2-3 minutes!"
echo ""

# Check if user wants to try CLI deployment
echo "💻 Alternative: CLI Deployment"
echo ""
echo "If you prefer command line:"
echo "1. vercel login (authenticate with GitHub)"
echo "2. vercel --prod (deploy)"
echo ""

echo "🔗 Current GitHub Repository:"
echo "https://github.com/SteppieD/blueprint"
echo ""
echo "📱 Current Live Demo:"
echo "https://blueprint-material-analyzer-aq6u18649-danger-dangers-projects.vercel.app"